// scripts/generate-tickers.mjs
// Run once: node scripts/generate-tickers.mjs
// Fetches NSE equity list and writes lib/nse-tickers.ts + scripts/nse-tickers.json

import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const NSE_EQUITY_URL =
  "https://nsearchives.nseindia.com/content/equities/EQUITY_L.csv";

const res = await fetch(NSE_EQUITY_URL, {
  headers: {
    "User-Agent":
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
    Accept: "text/csv,*/*",
    Referer: "https://www.nseindia.com/",
  },
});

if (!res.ok) throw new Error(`Failed to fetch NSE equity list: ${res.status}`);

const csv = await res.text();
const lines = csv.split("\n").slice(1); // skip header

const tickers = [];
for (const line of lines) {
  if (!line.trim()) continue;
  const cols = line.split(",");
  const symbol = cols[0]?.trim().replace(/^"|"$/g, "");
  const series = cols[2]?.trim().replace(/^"|"$/g, "");
  if (symbol && series === "EQ") {
    tickers.push(symbol);
  }
}

tickers.sort();

// Split into 3 roughly equal groups for 3 sheet tabs
const third = Math.ceil(tickers.length / 3);
const tabSplits = {
  Stock_1: tickers.slice(0, third),
  Stock_2: tickers.slice(third, third * 2),
  Stock_3: tickers.slice(third * 2),
};

// Write JSON data file (used by setup-sheet.mjs without TS compilation)
const jsonPath = join(__dirname, "nse-tickers.json");
writeFileSync(jsonPath, JSON.stringify(tabSplits, null, 2));
console.log(`Written tab splits to scripts/nse-tickers.json`);

// Write TypeScript source file (used by the Next.js app at runtime)
const tsContent = `// AUTO-GENERATED by scripts/generate-tickers.mjs
// Last updated: ${new Date().toISOString().split("T")[0]}
// Source: NSE EQUITY_L.csv (EQ series only)
// Total: ${tickers.length} tickers
// DO NOT EDIT MANUALLY — run scripts/generate-tickers.mjs to refresh

export const NSE_TICKERS: string[] = ${JSON.stringify(tickers, null, 2)};
`;

const tsPath = join(__dirname, "../lib/nse-tickers.ts");
writeFileSync(tsPath, tsContent);
console.log(`Written ${tickers.length} tickers to lib/nse-tickers.ts`);
console.log(`  Tab Stock_1: ${tabSplits.Stock_1.length} tickers`);
console.log(`  Tab Stock_2: ${tabSplits.Stock_2.length} tickers`);
console.log(`  Tab Stock_3: ${tabSplits.Stock_3.length} tickers`);
