// scripts/setup-sheet.mjs
// Run ONCE to set up Google Sheet tabs with GOOGLEFINANCE formulas.
// Requires: GOOGLE_SHEET_ID and GOOGLE_SERVICE_ACCOUNT_JSON in .env.local
// Also requires: scripts/nse-tickers.json (generated by scripts/generate-tickers.mjs)
// Run: node --env-file=.env.local scripts/setup-sheet.mjs

import { readFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ── Google Auth (inline JS — no TS import needed) ─────────────────────────────
function b64url(str) {
  return btoa(str).replace(/\+/g, "-").replace(/\//g, "_").replace(/=/g, "");
}
function b64urlBuf(buf) {
  const bytes = new Uint8Array(buf);
  let s = "";
  bytes.forEach((b) => (s += String.fromCharCode(b)));
  return btoa(s).replace(/\+/g, "-").replace(/\//g, "_").replace(/=/g, "");
}
function pemToDer(pem) {
  const b64 = pem.replace(/-----[^-]+-----/g, "").replace(/\s/g, "");
  const bin = atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
  return arr.buffer;
}
async function getToken() {
  const sa = JSON.parse(process.env.GOOGLE_SERVICE_ACCOUNT_JSON);
  const pk = sa.private_key.replace(/\\n/g, "\n");
  const now = Math.floor(Date.now() / 1000);
  const hdr = b64url(JSON.stringify({ alg: "RS256", typ: "JWT" }));
  const pay = b64url(JSON.stringify({
    iss: sa.client_email,
    scope: "https://www.googleapis.com/auth/spreadsheets",
    aud: "https://oauth2.googleapis.com/token",
    iat: now, exp: now + 3600,
  }));
  const key = await crypto.subtle.importKey("pkcs8", pemToDer(pk),
    { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" }, false, ["sign"]);
  const sig = await crypto.subtle.sign("RSASSA-PKCS1-v1_5", key,
    new TextEncoder().encode(`${hdr}.${pay}`));
  const jwt = `${hdr}.${pay}.${b64urlBuf(sig)}`;
  const r = await fetch("https://oauth2.googleapis.com/token", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({ grant_type: "urn:ietf:params:oauth:grant-type:jwt-bearer", assertion: jwt }),
  });
  const data = await r.json();
  if (!data.access_token) throw new Error(`Token error: ${JSON.stringify(data)}`);
  return data.access_token;
}

async function addTab(sheetId, name, token) {
  const r = await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${sheetId}:batchUpdate`, {
    method: "POST",
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify({ requests: [{ addSheet: { properties: { title: name } } }] }),
  });
  const body = await r.text();
  if (!r.ok && !body.includes("already exists")) throw new Error(`Add tab ${name}: ${body}`);
  console.log(`  Tab "${name}": ${body.includes("already exists") ? "already exists" : "created"}`);
}

async function writeRange(sheetId, range, values, token) {
  const url = `https://sheets.googleapis.com/v4/spreadsheets/${sheetId}/values/${encodeURIComponent(range)}?valueInputOption=USER_ENTERED`;
  const r = await fetch(url, {
    method: "PUT",
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify({ range, majorDimension: "ROWS", values }),
  });
  if (!r.ok) throw new Error(`Write ${range}: ${await r.text()}`);
}

async function sleep(ms) { return new Promise((r) => setTimeout(r, ms)); }

async function writeBatched(sheetId, tabName, rows, token, batchSize = 100) {
  for (let i = 0; i < rows.length; i += batchSize) {
    const chunk = rows.slice(i, i + batchSize);
    const startRow = i + 1;
    await writeRange(sheetId, `${tabName}!A${startRow}:C${startRow + chunk.length - 1}`, chunk, token);
    console.log(`    Wrote rows ${startRow}–${startRow + chunk.length - 1}`);
    if (i + batchSize < rows.length) await sleep(1200);
  }
}

// ── Main ──────────────────────────────────────────────────────────────────────
const SHEET_ID = process.env.GOOGLE_SHEET_ID;
if (!SHEET_ID) throw new Error("GOOGLE_SHEET_ID not set in .env.local");

// Read JSON data written by scripts/generate-tickers.mjs
const tabSplitsRaw = readFileSync(join(__dirname, "nse-tickers.json"), "utf8");
const TAB_SPLITS = JSON.parse(tabSplitsRaw);

console.log("Getting Google access token...");
const token = await getToken();
console.log("Token obtained.\n");

// ── Stock tabs ────────────────────────────────────────────────────────────────
for (const [tabName, tickers] of Object.entries(TAB_SPLITS)) {
  console.log(`Setting up tab: ${tabName} (${tickers.length} tickers)`);
  await addTab(SHEET_ID, tabName, token);

  const rows = [["SYMBOL", "Close Prev", "Change %"]];
  tickers.forEach((symbol, i) => {
    const row = i + 2; // data starts at row 2
    rows.push([
      symbol,
      `=GOOGLEFINANCE("NSE:"&A${row},"closeyest")`,
      `=ROUND(((INDEX(GOOGLEFINANCE("NSE:"&A${row},"close",WORKDAY(TODAY(),-1)),2,2)/INDEX(GOOGLEFINANCE("NSE:"&A${row},"close",WORKDAY(TODAY(),-2)),2,2))-1)*100,2)`,
    ]);
  });

  await writeBatched(SHEET_ID, tabName, rows, token);
  console.log(`  Done.\n`);
}

// ── Indices tab ───────────────────────────────────────────────────────────────
console.log("Setting up tab: Indices");
await addTab(SHEET_ID, "Indices", token);

const INDICES_ROWS = [
  ["INDEX_KEY", "Name", "Close Prev", "Change %"],
  ["INDEXNSE:NIFTY_50",   "Nifty 50",     '=GOOGLEFINANCE("INDEXNSE:NIFTY_50","closeyest")',    '=ROUND(((INDEX(GOOGLEFINANCE("INDEXNSE:NIFTY_50","close",WORKDAY(TODAY(),-1)),2,2)/INDEX(GOOGLEFINANCE("INDEXNSE:NIFTY_50","close",WORKDAY(TODAY(),-2)),2,2))-1)*100,2)'],
  ["INDEXBOM:SENSEX",     "Sensex",        '=GOOGLEFINANCE("INDEXBOM:SENSEX","closeyest")',       '=ROUND(((INDEX(GOOGLEFINANCE("INDEXBOM:SENSEX","close",WORKDAY(TODAY(),-1)),2,2)/INDEX(GOOGLEFINANCE("INDEXBOM:SENSEX","close",WORKDAY(TODAY(),-2)),2,2))-1)*100,2)'],
  ["INDEXNSE:NIFTYBANK",  "Bank Nifty",    '=GOOGLEFINANCE("INDEXNSE:NIFTYBANK","closeyest")',    '=ROUND(((INDEX(GOOGLEFINANCE("INDEXNSE:NIFTYBANK","close",WORKDAY(TODAY(),-1)),2,2)/INDEX(GOOGLEFINANCE("INDEXNSE:NIFTYBANK","close",WORKDAY(TODAY(),-2)),2,2))-1)*100,2)'],
  ["INDEXNSE:NIFTY_IT",   "Nifty IT",      '=GOOGLEFINANCE("INDEXNSE:NIFTY_IT","closeyest")',     '=ROUND(((INDEX(GOOGLEFINANCE("INDEXNSE:NIFTY_IT","close",WORKDAY(TODAY(),-1)),2,2)/INDEX(GOOGLEFINANCE("INDEXNSE:NIFTY_IT","close",WORKDAY(TODAY(),-2)),2,2))-1)*100,2)'],
  ["INDEXNSE:NIFTY_PHARMA","Nifty Pharma", '=GOOGLEFINANCE("INDEXNSE:NIFTY_PHARMA","closeyest")', '=ROUND(((INDEX(GOOGLEFINANCE("INDEXNSE:NIFTY_PHARMA","close",WORKDAY(TODAY(),-1)),2,2)/INDEX(GOOGLEFINANCE("INDEXNSE:NIFTY_PHARMA","close",WORKDAY(TODAY(),-2)),2,2))-1)*100,2)'],
  ["INDEXNSE:NIFTY_AUTO",  "Nifty Auto",   '=GOOGLEFINANCE("INDEXNSE:NIFTY_AUTO","closeyest")',   '=ROUND(((INDEX(GOOGLEFINANCE("INDEXNSE:NIFTY_AUTO","close",WORKDAY(TODAY(),-1)),2,2)/INDEX(GOOGLEFINANCE("INDEXNSE:NIFTY_AUTO","close",WORKDAY(TODAY(),-2)),2,2))-1)*100,2)'],
  ["INDEXNSE:NIFTY_METAL", "Nifty Metal",  '=GOOGLEFINANCE("INDEXNSE:NIFTY_METAL","closeyest")',  '=ROUND(((INDEX(GOOGLEFINANCE("INDEXNSE:NIFTY_METAL","close",WORKDAY(TODAY(),-1)),2,2)/INDEX(GOOGLEFINANCE("INDEXNSE:NIFTY_METAL","close",WORKDAY(TODAY(),-2)),2,2))-1)*100,2)'],
  ["INDEXNSE:NIFTY_ENERGY","Nifty Energy", '=GOOGLEFINANCE("INDEXNSE:NIFTY_ENERGY","closeyest")', '=ROUND(((INDEX(GOOGLEFINANCE("INDEXNSE:NIFTY_ENERGY","close",WORKDAY(TODAY(),-1)),2,2)/INDEX(GOOGLEFINANCE("INDEXNSE:NIFTY_ENERGY","close",WORKDAY(TODAY(),-2)),2,2))-1)*100,2)'],
  ["INDEXNSE:NIFTY_FMCG",  "Nifty FMCG",  '=GOOGLEFINANCE("INDEXNSE:NIFTY_FMCG","closeyest")',   '=ROUND(((INDEX(GOOGLEFINANCE("INDEXNSE:NIFTY_FMCG","close",WORKDAY(TODAY(),-1)),2,2)/INDEX(GOOGLEFINANCE("INDEXNSE:NIFTY_FMCG","close",WORKDAY(TODAY(),-2)),2,2))-1)*100,2)'],
  ["INDEXNSE:NIFTY_REALTY","Nifty Realty", '=GOOGLEFINANCE("INDEXNSE:NIFTY_REALTY","closeyest")', '=ROUND(((INDEX(GOOGLEFINANCE("INDEXNSE:NIFTY_REALTY","close",WORKDAY(TODAY(),-1)),2,2)/INDEX(GOOGLEFINANCE("INDEXNSE:NIFTY_REALTY","close",WORKDAY(TODAY(),-2)),2,2))-1)*100,2)'],
];

await writeRange(SHEET_ID, "Indices!A1:D11", INDICES_ROWS, token);
console.log("  Done.\n");

// ── Meta tab ──────────────────────────────────────────────────────────────────
console.log("Setting up tab: Meta");
await addTab(SHEET_ID, "Meta", token);
await writeRange(SHEET_ID, "Meta!A1:B1", [["last_recalc_trigger", new Date().toISOString()]], token);
console.log("  Done.\n");

console.log("Sheet setup complete.");
console.log("\nNext steps:");
console.log("1. Open the sheet — formulas take 5-15 min to compute on first load");
console.log("2. Publish each tab as CSV: File > Share > Publish to web > [tab] > CSV");
console.log("3. Add CSV URLs to .env.local:");
console.log("   SHEET_CSV_STOCK1=https://docs.google.com/spreadsheets/d/SHEET_ID/gviz/tq?tqx=out:csv&sheet=Stock_1");
console.log("   SHEET_CSV_STOCK2=...&sheet=Stock_2");
console.log("   SHEET_CSV_STOCK3=...&sheet=Stock_3");
console.log("   SHEET_CSV_INDICES=...&sheet=Indices");
